// @vitest-environment jsdom
import { afterEach, describe, expect, it, vi } from "vitest";
import { WebPdfDeliveryAdapter, type GeneratedPdfFile, type PdfDeliveryAdapter } from "../pdfDelivery";

afterEach(() => {
  vi.unstubAllGlobals();
  vi.restoreAllMocks();
});

describe("PDF delivery boundary", () => {
  it("allows native delivery to consume generated bytes without report business logic", async () => {
    const delivered: GeneratedPdfFile[] = [];
    const nativeFutureAdapter: PdfDeliveryAdapter = {
      async deliver(file) { delivered.push(file); },
    };
    const file = { filename: "User Name-2026-08-10-to-2026-08-16.pdf", bytes: new ArrayBuffer(4) };

    await nativeFutureAdapter.deliver(file);
    expect(delivered).toEqual([file]);
  });

  it("downloads the generated file through the browser adapter", async () => {
    const click = vi.spyOn(HTMLAnchorElement.prototype, "click").mockImplementation(() => {});
    const createObjectURL = vi.fn(() => "blob:wage-tracker-report");
    const revokeObjectURL = vi.fn();
    vi.stubGlobal("URL", { ...URL, createObjectURL, revokeObjectURL });

    await new WebPdfDeliveryAdapter().deliver({
      filename: "User Name-2026-08-10-to-2026-08-16.pdf",
      bytes: new Uint8Array([37, 80, 68, 70]).buffer,
    });

    expect(createObjectURL).toHaveBeenCalledOnce();
    expect(click).toHaveBeenCalledOnce();
    expect(revokeObjectURL).toHaveBeenCalledWith("blob:wage-tracker-report");
    expect(document.querySelector("a[download]")).toBeNull();
  });
});
