/**
 * A curated, maintainable blocklist of common/weak passwords and passphrases.
 *
 * This is deliberately a short, hand-picked list rather than a bundled
 * 10k/100k-entry breach corpus — easy to read, diff, and extend in review,
 * which is what "maintainable" means for a project this size. It's checked
 * two ways by `passwordPolicy.ts`:
 *
 *   1. Exact match against the fully normalized (lowercased, non-alphanumeric
 *      stripped) candidate password.
 *   2. Substring match for entries of MIN_SUBSTRING_MATCH_LENGTH+ characters,
 *      so padded/decorated variants like "password12345678" or
 *      "iloveyou-forever-2026" are still caught even though they aren't a
 *      literal 1:1 match with anything below.
 *
 * Add to this list as needed — it's plain data, no logic lives here.
 */
export const COMMON_PASSWORD_BLOCKLIST: readonly string[] = [
  // Classic top-of-the-list passwords
  "123456",
  "123456789",
  "12345678",
  "1234567890",
  "12345",
  "1234567",
  "111111",
  "000000",
  "123123",
  "654321",
  "666666",
  "555555",
  "121212",
  "112233",
  "qwerty",
  "qwerty123",
  "qwertyuiop",
  "asdfghjkl",
  "zxcvbnm",
  "1q2w3e4r5t",
  "1qaz2wsx",
  "abcdefgh",
  "abcd1234",
  "1a2b3c4d",
  "aaaaaaaa",
  "11111111",
  "00000000",
  "12341234",
  "87654321",
  "12312312",

  // Dictionary/passphrase-style favorites
  "password",
  "passw0rd",
  "p@ssword",
  "p@ssw0rd",
  "password1",
  "password12",
  "password123",
  "password1234",
  "letmein",
  "letmein1",
  "letmein123",
  "letmein12345",
  "welcome",
  "welcome1",
  "welcome123",
  "changeme",
  "changeme123",
  "changeme12345",
  "admin",
  "admin123",
  "root123",
  "login",
  "master",
  "master123",
  "monkey",
  "monkey123",
  "dragon",
  "dragon123",
  "sunshine",
  "sunshine1",
  "princess",
  "princess1",
  "football",
  "football1",
  "football123",
  "baseball",
  "baseball1",
  "basketball",
  "soccer",
  "superman",
  "superman1",
  "starwars",
  "starwars1",
  "trustno1",
  "trustno1234",
  "whatever",
  "whatever1",
  "whatever2",
  "freedom",
  "shadow",
  "shadow123",
  "iloveyou",
  "iloveyou1",
  "iloveyou2",
  "iloveyou123",
  "hunter2",
  "hunter123",
  "hello",
  "hockey",
  "ranger",
  "harley",
  "hannah",
  "jasmine",
  "thunder",
  "cookie",
  "summer",
  "cheese",
  "computer",
  "corvette",
  "chocolate",
  "purple",
  "orange",
  "ginger",
  "hammer",
  "silver",
  "richard",
  "merlin",
  "phoenix",
  "banana",
  "apples",
  "chelsea",
  "matthew",
  "patrick",
  "martin",
  "freddy",
  "gandalf",
  "alexander",
  "nicholas",
  "elephant",
  "butterfly",
  "dolphin",
  "dolphins",
  "michael",
  "michelle",
  "michelle1",
  "jennifer",
  "jessica",
  "samantha",
  "jordan",
  "charlie",
  "andrew",
  "andrea",
  "joshua",
  "maggie",
  "tigger",
  "robert",
  "buster",
  "daniel",
  "taylor",
  "william",
  "thomas",
  "ashley",
  "bailey",

  // Longer/passphrase-shaped weak passwords (relevant now that the minimum
  // length is 15 — length alone doesn't make these safe)
  "correcthorsebatterystaple",
  "thisismypassword",
  "mysecretpassword",
  "secretpassword",
  "newpassword",
  "newpassword123",
  "testpassword",
  "testpassword1",
  "testing123",
  "defaultpassword",
  "defaultpass",
  "temppassword",
  "temppass123",
  "welcometothejungle",
  "iloveyouforever",
  "foreverandever",

  // Obvious keyboard-walk / filler patterns
  "qwertyuiopasdfgh",
  "1234567890123456",
  "abcdefghijklmnop",
] as const;

/**
 * Application-specific terms that must never appear in a password, on top of
 * the general blocklist above (e.g. "MyWageTracker2026!" would otherwise
 * sail past the general list, but obviously ties the password to the app).
 * Checked the same way (normalized substring match).
 */
export const APP_SPECIFIC_BLOCKLIST: readonly string[] = [
  "wagetracker",
  "wagestracker",
  "wagetrackerapp",
  "wagetrackerpro",
];
